# promise基本使用

## 通过例子了解promise

JavaScript是单线程的，为了实现类多线程，最先使用事件及回调解决。

```JS
var img1 = document.querySelector('.img-1');

function loaded() {
  // image loaded
}

if (img1.complete) {
  loaded();
}
else {
  img1.addEventListener('load', loaded);
}

img1.addEventListener('error', function() {
  // argh everything's broken
});
```
以上事件会在事情触发后执行，但会带来两个问题：

1. 如果在图片出错后绑定事件，错误就无法监听到；
2. 对于多张图片按序加载或判断加载成功或失败，以上的判断都过于复杂；

我们希望比较理想的伪代码如下：

```JS
img1.callThisIfLoadedOrWhenLoaded(function() {
  // loaded
}).orIfFailedCallThis(function() {
  // failed
});

// and…
whenAllTheseHaveLoaded([img1, img2]).callThis(function() {
  // all loaded
}).orIfSomeFailedCallThis(function() {
  // one or more failed
});
```

以上方法就是类promise的实现，如果我们把图片的加载写成一个可以返回promise的“ready”，以上代码用promise实现就是：
```JS
img1.ready().then(function() {
  // loaded
}, function() {
  // failed
});

// and…
Promise.all([img1.ready(), img2.ready()]).then(function() {
  // all loaded
}, function() {
  // one or more failed
});
```

相对于事件监听器，promise有以下两点不同：

1. promise的状态是不可逆的，只可以成功或失败一次；
2. 如果添加了已解决状态的回调，就会按照对应回调正确执行；

## promise基本术语

- 已执行(resolve)：promise执行操作成功；
- 已拒绝(reject)：promise执行操作失败；
- 待定(pending)：尚未执行或拒绝；
- 已解决(fulfill)：已执行或拒绝

其中，promise与相应类库都符合名为promise/A+的常见化标准行为，promise/A+标准行为见[补充文档](https://github.com/lpldplws/promise_learning/blob/master/article/5.promise%E6%A0%87%E5%87%86%E5%8C%96%E8%A1%8C%E4%B8%BA%E8%A7%84%E8%8C%83%EF%BC%9ApromiseA%2B.md)。

在JavaScript中，创建promise的形式如下：

```JS
var promise = new Promise(function(resolve, reject) {
  // do a thing, possibly async, then…

  if (/* everything turned out fine */) {
    resolve("Stuff worked!");
  }
  else {
    reject(Error("It broke"));
  }
});
```

使用示例：

```JS
promise.then(function(result) {
  console.log(result); // "Stuff worked!"
}, function(err) {
  console.log(err); // Error:"It broke"
});
```

且在JavaScript中的promise API中，任何thenable的结构都可以当作promise处理，因此对于其他的类库也很好兼容。其中对于jQuery的Deferred需要人工转化成JavaScript promise：

```JS
var jsPromise = Promise.resolve($.ajax('/whatever.json'))
```

其中，$.ajax会生成一个thenable的Deferred，Promise.resolve会将符合thenable格式的对象转化成JavaScript promise。其中，deferred可以带有多个参数，但是JavaScript的deferred只会保留第一个。

```JS
var jqDeferred = $.ajax('/whatever.json');

jqDeferred.then(function(response, statusText, xhrObj) {
  // ...
}, function(xhrObj, textStatus, err) {
  // ...
})
jsPromise.then(function(response) {
  // ...
}, function(xhrObj) {
  // ...
})
```

但正常情况下，这个参数足以满足使用。

## 通过promise实例解决常见的异步问题

假设有一个场景：
1. loading；
2. 获取一个包括多标题的故事的JSON，确定每个标题与网址；
3. 添加标题；
4. 获取对应章节并添加到页面上；
6. 结束loading；

注意：发生问题时也要结束loading。

基于以上场景，我们可以按照如下的方式解决问题：

将请求封装成promise格式。

手写一个满足promise的get请求：

```JS
function get(url) {
  // Return a new promise.
  return new Promise(function(resolve, reject) {
    // Do the usual XHR stuff
    var req = new XMLHttpRequest();
    req.open('GET', url);

    req.onload = function() {
      // This is called even on 404 etc
      // so check the status
      if (req.status == 200) {
        // Resolve the promise with the response text
        resolve(req.response);
      }
      else {
        // Otherwise reject with the status text
        // which will hopefully be a meaningful error
        reject(Error(req.statusText));
      }
    };

    // Handle network errors
    req.onerror = function() {
      reject(Error("Network Error"));
    };

    // Make the request
    req.send();
  });
}
```

使用如下：

```JS
get('story.json').then(function(response) {
  console.log("Success!", response);
}, function(error) {
  console.error("Failed!", error);
})
```

其中：
1. 在then()里，只要return新值，就可以改变向后传递的值；
2. 在then()里，返回一个类promise的格式，下一个then()会等待，在promisefulfill的时候调用；
3. 多个then链式的写法，可以实现按序进行异步操作：

```JS
var promise = new Promise(function(resolve, reject) {
  resolve(1);
});

promise.then(function(val) {
  console.log(val); // 1
  return val + 2;
}).then(function(val) {
  console.log(val); // 3
})
```

因此，我们可以在then中添加JSON.parse来对返回值进行处理：

```JS
get('story.json').then(function(response) {
  return JSON.parse(response);
}).then(function(response) {
  console.log("Yey JSON!", response);
})
------------------------------------------------------------
get('story.json').then(JSON.parse).then(function(response) {
  console.log("Yey JSON!", response);
})
```

在此基础上，我们将JSON.parse提取出来，得到：

```JS
function getJSON(url) {
  return get(url).then(JSON.parse);
}
```

就可以得到story.json中第一章节地址中的内容：

```JS
getJSON('story.json').then(function(story) {
  return getJSON(story.chapterUrls[0]);
}).then(function(chapter1) {
  console.log("Got chapter 1!", chapter1);
})
```

再次将获取章节内容提取出来：

```JS
var storyPromise;

function getChapter(i) {
  storyPromise = storyPromise || getJSON('story.json');

  return storyPromise.then(function(story) {
    return getJSON(story.chapterUrls[i]);
  })
}

// and using it is simple:
getChapter(0).then(function(chapter) {
  console.log(chapter);
  return getChapter(1);
}).then(function(chapter) {
  console.log(chapter);
})
```

对于请求中的错误处理，我们有两种方式解决：

1. then()的第二个参数，用于处理失败情况；
2. catch()进行错误处理；

两者的变形如下：

```JS
get('story.json').then(function(response) {
  console.log("Success!", response);
}).catch(function(error) {
  console.log("Failed!", error);
})

get('story.json').then(function(response) {
  console.log("Success!", response);
}).then(undefined, function(error) {
  console.log("Failed!", error);
})
```

注意一点：两者之间的差异虽然很微小，但非常有用。 Promise 拒绝后，将跳至带有拒绝回调的下一个 then()（或具有相同功能的 catch()）。 如果是 then(func1, func2)，则 func1 或 func2 中的一个将被调用，而不会二者均被调用。 但如果是 then(func1).catch(func2)，则在 func1 拒绝时两者均被调用，因为它们在该链中是单独的步骤。

看一个典型的例子：

```JS
asyncThing1().then(function() {
  return asyncThing2();
}).then(function() {
  return asyncThing3();
}).catch(function(err) {
  return asyncRecovery1();
}).then(function() {
  return asyncThing4();
}, function(err) {
  return asyncRecovery2();
}).catch(function(err) {
  console.log("Don't worry about it");
}).then(function() {
  console.log("All done!");
})
```

流程图如下：
![流程图](https://developers.google.com/web/fundamentals/primers/imgs/promise-flow.svg?hl=zh-cn)

其中，如果promise被明确拒绝后，会执行reject，如果是在构造函数的回调中引发的错误，则会隐式拒绝，对于then()回调中的错误，也会隐式拒绝：

```JS
var jsonPromise = new Promise(function(resolve, reject) {
  // JSON.parse throws an error if you feed it some
  // invalid JSON, so this implicitly rejects:
  resolve(JSON.parse("This ain't JSON"));
});

jsonPromise.then(function(data) {
  // This never happens:
  console.log("It worked!", data);
}).catch(function(err) {
  // Instead, this happens:
  console.log("It failed!", err);
})
```

这说明在 promise 构造函数回调内部执行所有与 promise 相关的任务很有用，因为错误会自动捕获并进而拒绝。

对于以上代码添加完错误处理后，获取第一章节的内容就已经添加到页面上了，且健壮性也比较好：

```JS
getJSON('story.json').then(function(story) {
  return getJSON(story.chapterUrls[0]);
}).then(function(chapter1) {
  addHtmlToPage(chapter1.html);
}).catch(function() {
  addTextToPage("Failed to show chapter");
}).then(function() {
  document.querySelector('.spinner').style.display = 'none';
})
```

我们将获取每个章节的内容提取出来，会得到如下代码：

```JS
getJSON('story.json').then(function(story) {
  addHtmlToPage(story.heading);

  // TODO: for each url in story.chapterUrls, fetch &amp; display
}).then(function() {
  // And we're all done!
  addTextToPage("All done");
}).catch(function(err) {
  // Catch any error that happened along the way
  addTextToPage("Argh, broken: " + err.message);
}).then(function() {
  // Always hide the spinner
  document.querySelector('.spinner').style.display = 'none';
})
```

在不使用promise的情况下，我们之前遍历一般会这样做：

```JS
story.chapterUrls.forEach(function(chapterUrl) {
  // Fetch chapter
  getJSON(chapterUrl).then(function(chapter) {
    // and add it to the page
    addHtmlToPage(chapter.html);
  });
})
```

但是**forEach**不是异步的，最后添加到文章上的内容无法保证顺序，这里我们使用Promise.resolve(),它会将带有then方法的promise以相同的方式resolve/reject。

```JS
// Start off with a promise that always resolves
var sequence = Promise.resolve();

// Loop through our chapter urls
story.chapterUrls.forEach(function(chapterUrl) {
  // Add these actions to the end of the sequence
  sequence = sequence.then(function() {
    return getJSON(chapterUrl);
  }).then(function(chapter) {
    addHtmlToPage(chapter.html);
  });
})
```

使用Array.reduce修改为：

```JS
// Loop through our chapter urls
story.chapterUrls.reduce(function(sequence, chapterUrl) {
  // Add these actions to the end of the sequence
  return sequence.then(function() {
    return getJSON(chapterUrl);
  }).then(function(chapter) {
    addHtmlToPage(chapter.html);
  });
}, Promise.resolve())
```

综上：

```JS
getJSON('story.json').then(function(story) {
  addHtmlToPage(story.heading);

  return story.chapterUrls.reduce(function(sequence, chapterUrl) {
    // Once the last chapter's promise is done…
    return sequence.then(function() {
      // …fetch the next chapter
      return getJSON(chapterUrl);
    }).then(function(chapter) {
      // and add it to the page
      addHtmlToPage(chapter.html);
    });
  }, Promise.resolve());
}).then(function() {
  // And we're all done!
  addTextToPage("All done");
}).catch(function(err) {
  // Catch any error that happened along the way
  addTextToPage("Argh, broken: " + err.message);
}).then(function() {
  // Always hide the spinner
  document.querySelector('.spinner').style.display = 'none';
})
```

但是以上的方式只能保证页面依次下载，通过promise.all，我们可以让页面异步下载，全部下载完后处理：

```JS
getJSON('story.json').then(function(story) {
  addHtmlToPage(story.heading);

  // Take an array of promises and wait on them all
  return Promise.all(
    // Map our array of chapter urls to
    // an array of chapter json promises
    story.chapterUrls.map(getJSON)
  );
}).then(function(chapters) {
  // Now we have the chapters jsons in order!Loop through…
  chapters.forEach(function(chapter) {
    // …and add to the page
    addHtmlToPage(chapter.html);
  });
  addTextToPage("All done");
}).catch(function(err) {
  // catch any error that happened so far
  addTextToPage("Argh, broken: " + err.message);
}).then(function() {
  document.querySelector('.spinner').style.display = 'none';
})
```

以上是promise的一个使用场景，我们可以通过这个场景来理解promise的基本使用。