# 手写一个promise

<!-- TOC -->

- [手写一个promise](#手写一个promise)
    - [JavaScript Promise标准](#javascript-promise标准)
    - [逐步实现一个promise](#逐步实现一个promise)
        - [构造函数](#构造函数)
        - [then方法](#then方法)
        - [现有的promise错误处理](#现有的promise错误处理)
            - [链式无法传递值或抛出异常](#链式无法传递值或抛出异常)
            - [不同promise之间的交互：](#不同promise之间的交互)

<!-- /TOC -->

## JavaScript Promise标准

1. 只有一个then方法，没有catch，race，all等，也没有构造函数；另外，then也不支持像jQuery中$q的俗称为onProgress的第三个参数;
2. then方法会返回一个新的Promise;
```JS
promise2 = promise1.then(alert)
promise2 != promise1 // true
```
3. 不同Promise的实现需要可以相互调用;
4. Promise的初识状态为pending，可以转化为fulfilled（在JavaScript中我们俗称为resloved）或者rejected，状态是不可逆的，一旦转变就不可恢复，这个过程叫作settle;

具体的标准请看[5.promise标准化行为规范：promise/A+](https://github.com/lpldplws/promise_learning/blob/master/article/5.promise%E6%A0%87%E5%87%86%E5%8C%96%E8%A1%8C%E4%B8%BA%E8%A7%84%E8%8C%83%EF%BC%9ApromiseA%2B.md)

## 逐步实现一个promise

### 构造函数

我们按照ES6中原生的Promise的方式编写一个Promise对象：

```JS
// Promise构造函数接收一个executor函数，executor函数执行完同步或异步操作后，调用它的两个参数resolve和reject
let promise = new Promise((resolve, reject) => {
    // 操作成功，调用resolve并传value，
    // 操作失败，调用reject并传reason
});
```

对应的构造函数如下：

```JS
function Promise(executor) {
  var self = this; // 方便在实例中访问属性；
  self.status = 'pending'; // Promise当前的状态
  self.data = undefined;  // Promise的值
  self.onResolvedCallback = []; // Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
  self.onRejectedCallback = []; // Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面

  executor(resolve, reject) // 执行executor并传入相应的参数
}
```

定义到这步，我们还差两点没有完成：

1. executor的两个参数：resolve和reject没有定义;
2. 如果executor报错时，Promise构造函数应当throw出错误值并传给reject;

```JS
function Promise(executor) {
  var self = this
  self.status = 'pending' // Promise当前的状态
  self.data = undefined  // Promise的值
  self.onResolvedCallback = [] // Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
  self.onRejectedCallback = [] // Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面

  function resolve(value) {
    // TODO
  }

  function reject(reason) {
    // TODO
  }

  try { // 考虑到执行executor的过程中有可能出错，所以我们用try/catch块给包起来，并且在出错后以catch到的值reject掉这个Promise
    executor(resolve, reject) // 执行executor
  } catch(e) {
    reject(e)
  }
}
```

接下来补充resolve和reject：

```JS
function Promise(executor) {
  // ...

  function resolve(value) {
    if (self.status === 'pending') {
      self.status = 'resolved'
      self.data = value
      for(var i = 0; i < self.onResolvedCallback.length; i++) {
        self.onResolvedCallback[i](value)
      }
    }
  }

  function reject(reason) {
    if (self.status === 'pending') {
      self.status = 'rejected'
      self.data = reason
      for(var i = 0; i < self.onRejectedCallback.length; i++) {
        self.onRejectedCallback[i](reason)
      }
    }
  }

  // ...
}
```

### then方法

then方法用来注册Promise状态确定后的回调，因为是原型方法，需要写在原型链上。then会返回一个Promise，在JavaScript中，promise的then是返回一个新的promise对象，此处保持一致。

除此之外，每个Promise对象都可以在其上多次调用then方法，而每次调用then返回的Promise的状态取决于那一次调用then时传入参数的返回值，所以then不能返回this，因为then每次返回的Promise的结果都有可能不同。

```JS
// then方法接收两个参数，onResolved，onRejected，分别为Promise成功或失败后的回调
Promise.prototype.then = function(onResolved, onRejected) {
  var self = this
  var promise2

  // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
  onResolved = typeof onResolved === 'function' ? onResolved : function(v) {}
  onRejected = typeof onRejected === 'function' ? onRejected : function(r) {}

  if (self.status === 'resolved') {
    return promise2 = new Promise(function(resolve, reject) {

    })
  }

  if (self.status === 'rejected') {
    return promise2 = new Promise(function(resolve, reject) {

    })
  }

  if (self.status === 'pending') {
    return promise2 = new Promise(function(resolve, reject) {

    })
  }
}
```

Promise总共有三种可能的状态，我们分三个if块来处理，在里面分别都返回一个new Promise。

我们需要在then里面执行onResolved或者onRejected，并根据返回值(标准中记为x)来确定promise2的结果，并且，如果onResolved/onRejected返回的是一个Promise，promise2将直接取这个Promise的结果：

```JS
Promise.prototype.then = function(onResolved, onRejected) {
  var self = this
  var promise2

  // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
  onResolved = typeof onResolved === 'function' ? onResolved : function(value) {}
  onRejected = typeof onRejected === 'function' ? onRejected : function(reason) {}

  if (self.status === 'resolved') {
    // 如果promise1(此处即为this/self)的状态已经确定并且是resolved，我们调用onResolved
    // 因为考虑到有可能throw，所以我们将其包在try/catch块里
    return promise2 = new Promise(function(resolve, reject) {
      try {
        var x = onResolved(self.data)
        if (x instanceof Promise) { // 如果onResolved的返回值是一个Promise对象，直接取它的结果做为promise2的结果
          x.then(resolve, reject)
        }
        resolve(x) // 否则，以它的返回值做为promise2的结果
      } catch (e) {
        reject(e) // 如果出错，以捕获到的错误做为promise2的结果
      }
    })
  }

  // 此处与前一个if块的逻辑几乎相同，区别在于所调用的是onRejected函数，就不再做过多解释
  if (self.status === 'rejected') {
    return promise2 = new Promise(function(resolve, reject) {
      try {
        var x = onRejected(self.data)
        if (x instanceof Promise) {
          x.then(resolve, reject)
        }
      } catch (e) {
        reject(e)
      }
    })
  }

  if (self.status === 'pending') {
  // 如果当前的Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected，
  // 只能等到Promise的状态确定后，才能确实如何处理。
  // 所以我们需要把我们的**两种情况**的处理逻辑做为callback放入promise1(此处即this/self)的回调数组里
  // 逻辑本身跟第一个if块内的几乎一致，此处不做过多解释
    return promise2 = new Promise(function(resolve, reject) {
      self.onResolvedCallback.push(function(value) {
        try {
          var x = onResolved(self.data)
          if (x instanceof Promise) {
            x.then(resolve, reject)
          }
        } catch (e) {
          reject(e)
        }
      })

      self.onRejectedCallback.push(function(reason) {
        try {
          var x = onRejected(self.data)
          if (x instanceof Promise) {
            x.then(resolve, reject)
          }
        } catch (e) {
          reject(e)
        }
      })
    })
  }
}

// 为了下文方便，我们顺便实现一个catch方法
Promise.prototype.catch = function(onRejected) {
  return this.then(null, onRejected)
}
```

至此，我们基本实现了Promise标准中定义的内容，但是：

1. 对于以下情况：
```JS
new Promise(resolve=>resolve(8))
  .then()
  .then()
  .then(function foo(value) {
    alert(value)
  })
```

我们的代码是返回undefined，也就是值无法穿透到最后一个promise的foo里的实参；
2. 不同promise之间如果符合thenable是可以interactable(可交互)的，我们只判断了onResolved/onRejected的返回值是否为我们实现的Promise的实例，没有做任何其它的判断，所以这个标准是行不通的;

### 现有的promise错误处理

#### 链式无法传递值或抛出异常

对于第一个问题，我们通过转变代码为：

```JS
new Promise(resolve=>resolve(8))
  .then(function(value){
    return value
  })
  .catch(function(reason){
    throw reason
  })
  .then(function(value) {
    alert(value)
  })
```

可以看出，如果想向后传递promise的值，意味着then的两个参数的默认值分别为function(value) {return value}，function(reason) {throw reason}。

```JS
onResolved = typeof onResolved === 'function' ? onResolved : function(value) {return value}
onRejected = typeof onRejected === 'function' ? onRejected : function(reason) {throw re
```

只要将默认的参数值向后传递或者直接抛出异常即可。

对于第二个问题：

#### 不同promise之间的交互：